# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Tristan Huntington
# Description of the Site
description: Technical & Product Expertise
# URL of Image of the Site
site-image: /
# Keywords of the Site
site-keywords: Tristan, Computes, Consulting, Mobile App, Product Management, Product, Mobile
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/373076/pexels-photo-373076.jpeg?cs=srgb&dl=pexels-pixabay-373076.jpg&fm=jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: tristan@tristancomputes.com
#facebook_username: thedevslot
twitter_username: tristancomputes
#instagram_username: thedevslot
linkedin_username: tristanhuntington
github_username:  htristan
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: G-S7ZR7BRTC1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Tristan Huntington
# URL for the Image of the Author
author-image: /assets/images/Tristan-small.jpg
# 60 Words About the Author
author-about: Tristan is an experienced computer engineer, app builder, and business and product manager.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/htristan

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
# plugins:
#   - jekyll-admin
#   - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
